### PR TITLE
Change DB to mysql

### PR DESCRIPTION
**Pull request by chaspy**
- Change DB to MySQL:5.7.23
- Data persistence

### CODE REVIEW

**Comment by chaspy** [comment]
I confirmed that data saved in mysql container.

0. remove related docker-images
1. `docker-compose build` (takes much time 😢 )
2. `docker-compose up -d`
3. `curl localhost:9000` (takes some times)
4. access to localhost:9000 in my browser, and input account name to the form
5. check DB

```
$ docker exec -it cheerhawks_db_1 mysql -proot cheerhawks -e "select * from checks;"
mysql: [Warning] Using a password on the command line interface can be insecure.
+----+---------+--------------------------------------+----------------------------+----------------------------+
| id | name    | result                               | created                    | modified                   |
+----+---------+--------------------------------------+----------------------------+----------------------------+
|  1 | chaspy_ | chaspy_???????????????? ???????????? | 2018-08-08 17:22:29.797000 | 2018-08-08 17:22:29.797000 |
+----+---------+--------------------------------------+----------------------------+----------------------------+
```

@kamontia 
I want to talk with you about mysql root password

**Comment by chaspy** [comment]
resolve the problem about character-code
ref: https://github.com/kamontia/cheerHawks/pull/5/commits/39b26b394f68cd389acbfe88104c1e61dbb35f12

```
$ docker exec -it cheerhawks_db_1 mysql -proot cheerhawks -e "select * from checks;"
mysql: [Warning] Using a password on the command line interface can be insecure.
+----+---------+-------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
| id | name    | result                                                                                                            | created                    | modified                   |
+----+---------+-------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
|  1 | chaspy_ | chaspy_さんが応援すべきホークスの選手は 、「アルフレド・デスパイネ」選手です。                                    | 2018-08-08 17:53:12.819000 | 2018-08-08 17:53:12.819000 |
+----+---------+-------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
```

**Comment by chaspy** [comment]
##  How to reproduce

1. `docker system prune` if you want
2. `docker rmi kamontia/cheerhawks`
3. `docker-compose up -d` (it takes a lot of time...)
4. `curl localhost:9000` after you wait 10 or more second
  - it may return `curl: (52) Empty reply from server` but retry!
5.  access to localhost:9000 in my browser, and input account name to the form
6. `docker exec -it cheerhawks_db_1 mysql -proot cheerhawks -e "select * from checks;"`

```
MacBook-Air-3% docker exec -it cheerhawks_db_1 mysql -proot cheerhawks -e "select * from checks;"
mysql: [Warning] Using a password on the command line interface can be insecure.
+----+---------+-------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
| id | name    | result                                                                                                            | created                    | modified                   |
+----+---------+-------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
|  1 | chaspy_ | chaspy_さんが応援すべきホークスの選手は 、「アルフレド・デスパイネ」選手です。                                    | 2018-08-09 13:18:17.281000 | 2018-08-09 13:18:17.281000 |
+----+---------+-------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------+
```

**Comment by kamontia** [comment]
Thank you for your effort.

**Pull request merged**
